SLADIN-187 removed monitoring-selection
ccims/paymentsystem-service-monitoring pull request #12
Opened 2020-08-31 08:31 UTC by JonasJW

## Preparations
Please check if the PR fulfills these requirements
- [ ] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [ ] Das Feature ist dokumentiert
- [ ] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-09-09 13:14 UTC, stiesssh commented
bitte PR template nutzen - soll heißen : füllt es auch aus!

2020-09-11 19:59 UTC, stiesssh requested changes

2020-09-11 19:59 UTC, stiesssh commented on payment-service-monitor/src/app.controller.ts
> -    }
doc comment anpassen. im kommentar, wird immernoch behauptete, dass diese methode zuerst überprüft, ob ein service überhaupt gemonitored wird. 
warum wird das eigentlich nicht mehr überprüft? eine anmerkung im sinne von 'es wird angenommen, dass der service tatsächlich gemonitored wird, dies wird von X sicher gestellt' wäre cool.

2020-09-12 08:55 UTC, JonasJW commented on payment-service-monitor/src/app.controller.ts
> -    }
Das überprüfen findet jetzt im issue-creator selber statt

2020-09-15 07:37 UTC, stiesssh approved these changes

2020-09-15 09:17 UTC, merged