SLADIM-79
ccims/paymentsystem-service-monitoring pull request #6
Opened 2020-07-28 12:12 UTC by JonasJW

## Preparations
Please check if the PR fulfills these requirements
- [x] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [x] Das Feature ist dokumentiert
- [x] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [x] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-07-28 12:31 UTC, stiesssh requested changes

2020-07-28 12:31 UTC, stiesssh commented on payment-service-monitor/src/app.controller.ts
> +   * @param error sent by price service
'and and' ? ein 'and' ist m.e. ausreichend.

@returns fehlt.

2020-07-28 12:31 UTC, stiesssh commented on payment-service-monitor/src/app.service.ts
> +   */
'ne' = 'be' ?

2020-07-28 12:31 UTC, stiesssh commented on payment-service-monitor/src/app.service.ts
>     * @returns the messages array containing all messages
leerzeile vor den tags

2020-07-28 12:31 UTC, stiesssh commented on payment-service-monitor/src/app.service.ts
>     */
erst fließtext beschreibung, dann tags.

2020-07-28 12:31 UTC, stiesssh commented on payment-service-monitor/src/app.service.ts
>     * creation of a log message and pushing that message into array 'messages'
erst fließtext beschreibung, dann tags.

2020-07-28 12:33 UTC, stiesssh commented
außerdem versuchen die tests immernoch eine nicht vorhandene `getHello()` methode zu testen. das bitte auch fixen.

2020-07-28 12:53 UTC, JonasJW commented
Die Kommentare waren zwar nicht von mir aber ich kann die auch kurz bearbeiten 😁

2020-07-28 13:02 UTC, stiesssh commented
test schlagen immer noch fehl - jetzt wegen den imports ;) 
hatte nicht irgendjemand demletzt rausgefunden, wie man die imports ändern muss, damit die tests funktionieren?

2020-07-28 13:02 UTC, stiesssh approved these changes

2020-07-29 16:02 UTC, MarcelWolkober approved these changes

2020-07-29 16:08 UTC, merged