Sladim 117
ccims/paymentsystem-service-monitoring pull request #9
Opened 2020-08-18 07:00 UTC by tobiasrodestock

## Preparations
Please check if the PR fulfills these requirements
- [ ] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [ ] Das Feature ist dokumentiert
- [ ] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [ ] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added kafka mq

* **What is the current behavior?** (You can also link to an open issue here)
Logs are sent directly to the issue creator by the monitoring services

* **What is the new behavior (if this is a feature change)?**
Errors are now sent to the kafka mq

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
There is a docker compose in this repo to setup kafka

## :lock: Closes
Which issue(s) is (are) being closed by the PR?
SLADIM-117

2020-08-20 05:41 UTC, stiesssh commented on payment-service-monitor/src/app.service.ts
> +  brokers: ['localhost:9092']
seid ihr nicht schon so weit gewesen, dass ihr keine hardcoded urls mehr verwendet? oder was das _nur_ im monitoring-frontend?

2020-08-20 06:05 UTC, stiesssh requested changes
Desweitern: unter den fehlschlagenden tests, scheint einer zu sein, desse fehlschlagen anscheinend direkt auf kafka zurück zuführen ist : 

 FAIL src/request-sender/request-sender.service.spec.ts
  Test suite failed to run
 Cannot find module 'kafkajs' from 'app.service.ts'

    Require stack:
      app.service.ts
      request-sender/request-sender.service.ts
      request-sender/request-sender.service.spec.ts

      2 | import { IssueLoggingService } from 'logging-module';
      3 | import { LogMessageFormat, ErrorFormat } from 'logging-format';
    > 4 | const {Kafka} = require('kafkajs');
        |                 ^
      5 | 
      6 | const kafka = new Kafka({
      7 |   clientId: 'error-monitor',

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> (app.service.ts:4:17)

könnt ihr das fixen? Also nicht alles test, sondern nur jene, die mit den von euch getätigten änderungen zusammenhängen.

2020-08-24 08:21 UTC, stiesssh commented
> Lokal funktionieren die Tests, ich bin mir nur nicht sicher wie sinnvoll es ist hier die MQ zu mocken

ich halte es für sinnvoll. mit einem solchen test kann man, ohne eine MQ starten zu müssen, prüfen, ob die kommunikation mit dieser funktioniert. 
denke mal an dein future-self, und wie sehr es sich darüber freuen wird,  wenn es nur 'npm run test' ausführen muss und schon weiß ob der code noch tut. (im gegensatz zu der variante, in der dein future-self sich erst daran erinnern muss, wie das mit dem starten der lokalen MQ ging, bevor es test ausführen kann.)

2020-08-25 10:24 UTC, tobiasrodestock commented
Habe die MQ gemockt die unit tests funktionieren jetzt wieder

2020-08-25 10:48 UTC, stiesssh approved these changes

2020-08-25 10:49 UTC, stiesssh commented
> Habe die MQ gemockt die unit tests funktionieren jetzt wieder

sehr cool :+1:

2020-08-25 10:51 UTC, merged